# Generated by Django 4.2.2 on 2023-07-23 09:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=120)),
                ('Address', models.CharField(max_length=120)),
                ('Country', models.CharField(max_length=50)),
                ('Introduction', models.TextField()),
                ('Picture', models.ImageField(upload_to='Area/')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=80)),
                ('Body', models.TextField()),
                ('Picture', models.ImageField(upload_to='Area_Comment')),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.area')),
            ],
        ),
    ]
