# Generated by Django 4.2.2 on 2023-07-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Price', models.IntegerField()),
                ('Address', models.CharField(max_length=120)),
                ('Country', models.CharField(max_length=50)),
                ('Rating', models.IntegerField()),
                ('Introduction', models.TextField()),
                ('Picture', models.ImageField(upload_to='Shop/')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Body', models.TextField()),
                ('Photo', models.ImageField(upload_to='Comment/')),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Locate.shop')),
            ],
        ),
    ]
