# Generated by Django 4.2.2 on 2023-07-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Photo',
            field=models.ImageField(upload_to='Shop_Comment/'),
        ),
    ]
