# Generated by Django 4.2 on 2023-08-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locate', '0002_alter_comment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='People',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
